### ISSUE TITLE
Distribute objects masses and define within shape definition

### ISSUE THREAD

**Issue by bfeldpw** [planeworld/examples#13]
Since COM and inertia are calculated automatically by the objects shape, object-based masses are not valid any more. Mass has to be defined for each shape. Otherwise, a default value of 1.0 is assumed.
Note: This also causes the error of objects leaving their orbit, since orbited bodies have a default mass of 1.0.

**Comment by avanc** [comment]
Fixed with 6c4e94db2263f2b25719abd00cb2c395979f41de
